server:
  port: 8083

spring:
  application:
    name: project-service
  sql:
    init:
      mode: never
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

trackify:
  storage:
    location: ./uploads

services:
  notification-url: http://localhost:8084

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000
