server:
  port: 8083

spring:
  application:
    name: project-service
  sql:
    init:
      mode: never

jwt:
  secret: ${JWT_SECRET:8R6Hw7jW+fU3XzLmK2NpB5vC9aE4qG1tV0yA3xD7oZc=}
  expiration: 86400000
