server:
  port: 8084

spring:
  application:
    name: notification-service
  profiles:
    active: local
  config:
    import:
      - optional:classpath:trackify-management.yml
      - optional:classpath:trackify-env-imports.yml
  mail:
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true

jwt:
  expiration: 86400000
