spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

jwt:
  secret: ${JWT_SECRET}

tenant:
  datasource:
    host-override: ${TENANT_DATASOURCE_HOST_OVERRIDE:db}

logging:
  level:
    root: WARN
    com.trackify: INFO
