spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://db:3306/trackify_master?useSSL=false&allowPublicKeyRetrieval=true}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

services:
  notification-url: http://notification-service:8084
  project-url: http://project-service:8083

tenant:
  datasource:
    default-host: ${TENANT_DATASOURCE_DEFAULT_HOST:db}
  app-url-pattern: http://%s.localhost:3001
